//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "chatter_command")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    #[serde(skip_deserializing)]
    pub chatter_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    #[serde(skip_deserializing)]
    pub command_id: i64,
    pub count: i64,
    #[sea_orm(
        belongs_to,
        from = "chatter_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub chatter: HasOne<super::chatter::Entity>,
    #[sea_orm(
        belongs_to,
        from = "command_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub command: HasOne<super::command::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
