//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "chatter")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    #[serde(skip_deserializing)]
    pub id: i64,
    pub name: String,
    pub tid: i64,
    pub sid: i64,
    #[sea_orm(has_many, via = "chatter_command")]
    pub commands: HasMany<super::command::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
