//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::chatter::Entity as Chatter;
pub use super::chatter_command::Entity as ChatterCommand;
pub use super::command::Entity as Command;
pub use super::post::Entity as Post;
